# Generated by cpputils-cmake.
include /playpen/forZhiyuanDemo/ReadWrite/build/CMakeFiles/ReadWrite.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}